var LANG = "en";

var STRINGS = {
	"en": {
		"accountAskForSignUp": "Sign Up for an Account! srly like now for gaming!",
		"accountBack": "Back to Log In",
		"accountEmail": "Email",
		"accountExists": "Already have an account?",
		"accountForgot": "Forgot Username or Password? :C",
		"accountGuest": "Play as Guest...",
		"accountLogIn": "Log In, Tree?",
		"accountNeeded": "No account? :C (click to get)",
		"accountPassword": "Password, now.",
		"accountPasswordConfirm": "Confirm Password",
		"accountPitch": "- Gain XP and level up in the game!\n - Customize your tank's appearance!\n - Save your progress and stats!",
		"accountReset": "Password Reset",
		"accountResetDescription": "We've sent an email to you with instructions on resetting your password. <br><br> If you don't receive an email in the next few minutes, please contact",
		"accountSettings": "Account Info / Settings",
		"accountSignUp": "Sign Up now for gaming.",
		"accountUsername": "Username, yes.",
		"any": "Any",
		"appearance": "Appearance, like I appeared to you're Walls",
		"appearanceChange": "Change Appearance, BAM! I appear With many items.",
		"appearanceDarkMode": "Super Cool Dark Mode? :O",
		"appearanceDecals": "Decals, Nice Tank.",
		"appearanceExplosions": "Explosions from death!",
		"appearanceRotate": "Sticker Rotates With Tank Arm, Nice now they can be goofy on the arm.",
		"appearanceStickers": "Stickers = Perfect",
		"appearanceTankArm": "Arms for hands",
		"autoJoin": "Auto Join, why?",
		"awesome": "Awesome!",
		"beNice": "Please be nice in the chat so you won't get Chat Banned :)",
		"blueTeam": "Blue Team",
		"change": "Change",
		"changePassword": "Change Password, sus",
		"chatInstructions": "Press \"t\" to talk, Like wow and nice.",
		"congrats": "Congratulations!",
		"connecting": "Connecting your...",
		"contactLine1": "Report Bugs",
		"contactLine2": "Request Features",
		"contactMessage": "Are you sure you want to fill out a contact form? This will take you out of the game.",
		"controller": "Controller Support",
		"cpBlue": "The blue team has captured the Intelig- I mean control point! Get the CP.",
		"cpRed": "The red team has captured the Intelige- I mean control point! Get the CP.",
		"ctfBlue": "The blue team has captured the flag! Got it",
		"ctfRed": "The red team has captured the flag! Got it",
		"ctfStolen": "The other team has stolen your flag! OH NO!",
		"ctfReturn": "Return the flag to your base! (Hehehe)",
		"currentMap": "Map of death",
		"customItem": "Custom Item",
		"deathsAbbr": "D",
		"decline": "No Thanks",
		"discordConnect": "Connect Discord Account, Do you have one?",
		"discordConnect2": "Connect To Discord, If you have one.",
		"discordConnected": "Discord Connected! Nice.",
		"discordDescription": "Connect your Discord account to BlockTanks to join our server as a verified member.",
		"dropped": "Abandoning \"Deadly\"",
		"email": "Email",
		"error": "Error",
		"flashAim": "Right click or press F to aim, helpful info.",
		"flashSwap": "You have now swapped teams. (What the heck)",
		"getIt": "Get It Now!",
		"helpDescription": "Mouse to aim and shoot, H A M P T E R.. \nWASD to move = yes now i know how to move! \nTo change weapons, Pet the H A M P T E R, if not then, Press Massively on the Q/E buttons >:( \nHold TAB to uhhhh show the team table? or Leaderboard?. \nPress X to Abandon W E A P O N.",
		"helpSpectateDescription": "Left click to switch follow modes.\nWASD to move.\nUse the scroll wheel or Q and E to zoom.\nHold TAB to join a team.",
		"helpDescriptionMobile": "Drag the left joystick to move\nDrag the right joystick to aim, and release to shoot.\nTap weapons in the bottom right to select them. \nLong press a weapon to drop it.",
		"helpMenu": "Help Menu",
		"join": "Join the meme's",
		"kdAbbr": "K/D",
		"kdRatio": "Display K/D Ratios, nice.",
		"killedYou": "Exterminated you, gg.",
		"killsAbbr": "K",
		"killsDeathsRatio": "K/D Ratio",
		"killStreaks": "Kill Streaks are wow",
		"killFeed": "Display Kill Feed",
		"link1": "Supporters",
		"link2": "FAQ",
		"link3": "Contact",
		"link4": "Privacy Policy",
		"loading": "Loading Perfectly",
		"lobbyButton": "Game Lobby",
		"lobbyGamesTitle": "Game List",
		"lobbyLogout": "Logout, AAAAAAAAAA",
		"lobbyQuickJoin": "Quick Join",
		"lobbyTitle": "Lobby",
		"loser": "Loser! I thought you can do better.",
		"labs": "BlockTanks Labs",
		"mapVote": "Vote for the next map, i am very okay",
		"messageServerMove": "You were moved to a server with more players, Now fight.",
		"messageUnlock": "Sweet! You leveled up and unlocked some items!",
		"mode": "Mode",
		"modeCP": "Payload (CP)",
		"modeFFA": "Free-For-All (FFA)",
		"modeTDM": "Team Deathmatch (TDM)",
		"modeBR": "Battle Royale (BR)",
		"modeCTF": "Capture-the-Flag (CTF)",
		"modeObjCP": "Move the control point to the other team's base! now you got to pay the load",
		"modeObjFFA": "Shoot anything that moves! Like a bullet! (JK)",
		"modeObjTDM": "Kill tanks on the other team! They are your current \"Error\"?",
		"modeObjCTF": "Capture the other team's flag! Then They are here... (Nonsense)",
		"name": "Name here",
		"newItem": "You unlocked some new items! AMAZING!! :D",
		"okay": "Okay",
		"password": "Password now!",
		"pickedUp": "Collected \"Deadly\"",
		"play": "Play now!",
		"playerStats": "In-Game Player Stats. (SEES O_O)",
		"players": "players",
		"quitConfirm": "Are you sure you want to leave the match? (uh oh)",
		"ratio": "Ratio",
		"redTeam": "Red Team",
		"replays": "Record Match Replays",
		"report": "Report",
		"reportConfirm": "Are you sure you want to report this player? This will make you exit the current game.",
		"respawnClick": "Click to regain LIFE!",
		"respawnTimer": "Collecting your in-game life in",
		"restoreDefaults": "Restore Defaults",
		"save": "Save Now!",
		"sendUpdates": "Send updates for BlockTanks and future projects to this email?",
		"serverConnecting": "Connecting to a known Server...",
		"serverFind": "Trying to find a Greatful server...",
		"serverFound": "Server Found! Amazing now Connecting...",
		"serverLoading": "Loading Resources, Wait for it",
		"settings": "Settings",
		"size": "Size",
		"sizeBig": "Big",
		"sizeMedium": "Medium",
		"sizeSmall": "Small",
		"social": "Join the Community",
		"submit": "Submit",
		"supportButton": "Support The Game",
		"tie": "It's a Tie! Wow.",
		"timeUpBlue": "Time's Up - The Blue Team Wins! Wow",
		"timeUpRed": "Time's Up - The Red Team Wins! Nice",
		"timeUpTie": "Time's Up - It's a Tie! Aww",
		"updateTitle": "New Updates!",
		"viewInLobby": "View in Lobby",
		"vip": "VIP",
		"VIP-ask": "Become a BlockTanks VIP Member!",
		"VIP-button": "Buy for",
		"VIP-congrats": "Congratulations! You are now a VIP member!",
		"VIP-info1": "Some things to know:",
		"VIP-info2": "All in-game items have been unlocked!",
		"VIP-info3": "An email has been sent to you with your order confirmation/receipt.",
		"VIP-info4": "Your name (if you gave one in your order) will be added to the BlockTanks Hall of Fame!",
		"VIP-info5": "Your contribution directly supports the developer, and allows the game to continue to improve! Thank you!",
		"VIP-info6": "P.S: You should check the settings menu",
		"VIP-item": "Your custom item is on its way and should be in this menu shortly!",
		"VIP-pitch": "- Unlock all in-game items!\n- Receive a special VIP username label!\n- Remove all ads!",
		"weapon_bomb": "bomb, C4? no it's a ball with spikes lol.",
		"weapon_flashbang": "flashbang, How did you get this?",
		"weapon_grenade": "hand grenade.",
		"weapon_intro": "Collected \"Deadly\"",
		"weapon_rapid": "rapid bullets, wonderful.",
		"weapon_rocket": "rocket, He go boom.",
		"weapon_shotgun": "shotgun shells, Nice.",
		"weapon_sniper": "sniper bullets, Now do a 360.",
		"weapon_minigun": "minigun bullets, oh dear.",
		"weapon_bottlebomb": "bottle bomb, Alright.",
		"winner": "Winner! WOW :o",
		"XP-level": "Level",
		"XP-rank": "Rank",
		"youKilled": "You Eradicated"
	},
	"de": {
		"accountAskForSignUp": "Für einen Account anmelden",
		"accountBack": "Zurück zur Anmeldung",
		"accountEmail": "Email",
		"accountExists": "Hast du bereits ein Konto?",
		"accountForgot": "Nutzername oder Passwort vergessen?",
		"accountGuest": "Spiele als Gast",
		"accountLogIn": "Einloggen",
		"accountNeeded": "Brauchst du einen Account?",
		"accountPassword": "Passwort",
		"accountPasswordConfirm": "Passwort bestätigen",
		"accountPitch": "- Erhalte XP und steige im Spiel auf!\n- Passe das Aussehen deines Panzers an!\n- Speicher deine Fortschritte und Statistiken!",
		"accountReset": "Passwort zurücksetzen",
		"accountSettings": "Account Einstellungen",
		"accountSignUp": "Anmelden",
		"accountUsername": "Nutzername",
		"any": "Zufällig",
		"appearance": "Aussehen",
		"appearanceChange": "Aussehen ändern",
		"appearanceDarkMode": "Super cooler Dark-Modus?",
		"appearanceDecals": "Lackierung",
		"appearanceExplosions": "Explosion",
		"appearanceRotate": "Aufkleber dreht sich mit dem Panzerarm",
		"appearanceStickers": "Aufkleber",
		"appearanceTankArm": "Arm",
		"awesome": "Genial!",
		"beNice": "Sei bitte nett im Chat",
		"blueTeam": "Blaues Team",
		"change": "Wechseln",
		"changePassword": "Passwort ändern",
		"chatInstructions": "Drücke \"t\" zum sprechen",
		"congrats": "Herzlichen Glückwunsch!",
		"connecting": "Verbinden...",
		"contactLine1": "Fehler melden",
		"contactLine2": "Funktionen vorschlagen",
		"contactMessage": "Möchtest Du wirklich das Kontaktformular ausfüllen? Das wird dich aus dem Spiel werfen.",
		"controller": "Unterstützung für Gamepads",
		"cpBlue": "Das blaue Team hat den Kontrollpunkt eingenommen!",
		"cpRed": "Das rote Team hat den Kontrollpunkt eingenommen!",
		"currentMap": "Aktuelle Karte",
		"deathsAbbr": "T",
		"decline": "Nein, danke",
		"discordConnect": "Discord Konto verbinden",
		"discordConnect2": "Mit Discord verbinden",
		"discordConnected": "Discord verbunden!",
		"discordDescription": "Verbinden Sie Ihr Discord-Konto mit BlockTanks, um unserem Server als verifiziertes Mitglied beizutreten.",
		"dropped": "Fallen gelassen",
		"email": "Email",
		"error": "Error",
		"flashAim": "Rechtsklick oder drücke F um zu zielen.",
		"flashSwap": "Du hast das Team gewechselt.",
		"getIt": "Hol es jetzt!",
		"helpDescription": "Maus zum zielen und schießen.\nWASD zum bewegen.\nNutze das Mausrad oder Q und E um die Waffen zu wechseln.\nHalte TAB gedrückt, um die Teams anzuzeigen.\nHalte SHIFT gedrückt, um dieses Menü jederzeit anzuzeigen.",
		"helpMenu": "Hilfemenü",
		"join": "Beitreten",
		"kdAbbr": "K/D",
		"kdRatio": "K/D-Verhältnisse anzeigen",
		"killedYou": "hat dich getötet.",
		"killsAbbr": "K",
		"killsDeathsRatio": "K/D Verhältnis",
		"killStreaks": "Kill Streaks",
		"killFeed": "Kill-Feed anzeigen ",
		"link1": "Unterstützer",
		"link2": "FAQ",
		"link3": "Kontakt",
		"link4": "Datenschutz-Bestimmungen",
		"loading": "Lädt",
		"lobbyButton": "Game Lobby",
		"lobbyGamesTitle": "Spieleliste",
		"lobbyLogout": "Ausloggen",
		"lobbyQuickJoin": "Schnell beitritt",
		"lobbyTitle": "Lobby",
		"loser": "Verlierer!",
		"labs": "BlockTanks Labs",
		"mapVote": "Stimme für die nächste Karte",
		"messageServerMove": "Du wurdest auf einen Server mit mehr Spielern verlegt.",
		"messageUnlock": "Süß! Du bist aufgelevelt und hast neue Gegenstände freigeschaltet!",
		"mode": "Modus",
		"modeCP": "Kontrollpunkt",
		"modeObjCP": "Nehme den Kontrollpunkt ein!",
		"modeObjTDM": "Töte Panzer aus dem Gegnerischen Team!",
		"modeTDM": "Team Deathmatch",
		"name": "Name",
		"newItem": "Du hast einige neue Gegenstände freigeschaltet!",
		"okay": "Okay",
		"password": "Passwort",
		"pickedUp": "aufgehoben",
		"play": "Spielen!",
		"playerStats": "Spielerstatistiken anschauen",
		"players": "Spieler",
		"quitConfirm": "Möchtest du das Spiel wirklich verlassen?",
		"ratio": "Verhältnis",
		"redTeam": "Rotes Team",
		"replays": "Spielwiederholungen aufzeichnen",
		"report": "Melden",
		"reportConfirm": "Bist du sicher, dass du diesen Spieler melden willst?\nDadurch verlässt du das aktuelle Spiel.",
		"respawnClick": "Klicken zum wiederbeleben",
		"respawnTimer": "Wiederbeleben in",
		"restoreDefaults": "Standardeinstellungen wiederherstellen",
		"save": "Speichern",
		"sendUpdates": "Updates und zukünftige Projekte für BlockTanks an diese E-Mail senden?",
		"serverConnecting": "Verbindung zum Server herstellen...",
		"serverFind": "Versuche einen Server zu finden...",
		"serverFound": "Server gefunden! Verbinde...",
		"serverLoading": "Lade Ressourcen",
		"settings": "Einstellungen",
		"size": "Größe",
		"sizeBig": "Groß",
		"sizeMedium": "Mittel",
		"sizeSmall": "Klein",
		"social": "Trete der Community bei",
		"submit": "Einreichen",
		"supportButton": "Unterstütze das Spiel",
		"tie": "Es ist Unentschieden!",
		"timeUpBlue": "Die Zeit ist um - Das blaue Team hat gewonnen",
		"timeUpRed": "Die Zeit ist um - Das rote Team hat gewonnen!",
		"timeUpTie": "Die Zeit ist um - Es ist Unentschieden!",
		"updateTitle": "Neue Updates!",
		"viewInLobby": "Blick in die Lobby",
		"vip": "VIP",
		"VIP-ask": "Werde ein BlockTanks VIP Mitglied!",
		"VIP-button": "Kaufen für",
		"VIP-congrats": "Herzlichen Glückwunsch! Du bist jetzt ein VIP Mitglied!",
		"VIP-info1": "Einige Dinge zu wissen:",
		"VIP-info2": "Dein benutzerdefiniertes Item (Wenn du eins bestellt hast) sollte 3-5 Tage dauern. Wenn es für dich verfügbar ist, erhälst du eine Spielnachricht und dein Gegenstand erscheint im Menü der Gegenstände.",
		"VIP-info3": "Du hast eine Email mit deiner Bestätigung erhalten.",
		"VIP-info4": "Dein Name (wenn du einen in der Bestellung angegeben hast) wird in der BlockTanks Hall of Fame aufgenommen.",
		"VIP-info5": "Dein Beitrag unterstützt den Entwickler direkt und ermöglicht eine weitere Verbesserung des Spiels! Vielen Dank!",
		"VIP-info6": "P.S: Du solltest das Einstellungsmenü überprüfen",
		"VIP-item": "Dein VIP Item ist auf dem Weg und sollte in Kürze in diesem Menü sein!",
		"weapon_bomb": "Eine Bombe",
		"weapon_flashbang": "Eine Blendgranate.",
		"weapon_grenade": "Eine Handgranate",
		"weapon_intro": "aufgehoben",
		"weapon_rapid": "Ein Paar rapid Kugeln.",
		"weapon_rocket": "Eine Rakete",
		"weapon_shotgun": "Ein Paar Schrotpatronen",
		"weapon_sniper": "Ein Paar Scharfschützenpatronen.",
		"weapon_volcano": "Eine Vulkanbombe",
		"winner": "Gewinner!",
		"XP-level": "Level",
		"XP-rank": "Rang",
		"youKilled": "Du hast getötet"
	},
	"es": {
		"accountAskForSignUp": null,
		"accountBack": null,
		"accountEmail": null,
		"accountExists": null,
		"accountForgot": null,
		"accountGuest": null,
		"accountLogIn": null,
		"accountNeeded": null,
		"accountPassword": null,
		"accountPasswordConfirm": null,
		"accountPitch": null,
		"accountReset": null,
		"accountResetDescription": null,
		"accountSettings": null,
		"accountSignUp": null,
		"accountUsername": null,
		"any": null,
		"appearance": null,
		"appearanceChange": null,
		"appearanceDarkMode": null,
		"appearanceDecals": null,
		"appearanceExplosions": null,
		"appearanceRotate": null,
		"appearanceStickers": null,
		"appearanceTankArm": null,
		"autoJoin": null,
		"awesome": null,
		"beNice": null,
		"blueTeam": null,
		"change": null,
		"changePassword": null,
		"chatInstructions": null,
		"congrats": null,
		"connecting": null,
		"contactLine1": null,
		"contactLine2": null,
		"contactMessage": null,
		"controller": null,
		"cpBlue": null,
		"cpRed": null,
		"currentMap": null,
		"customItem": null,
		"deathsAbbr": null,
		"decline": null,
		"discordConnect": null,
		"discordConnect2": null,
		"discordConnected": null,
		"discordDescription": null,
		"dropped": null,
		"email": null,
		"error": null,
		"flashAim": null,
		"flashSwap": null,
		"getIt": null,
		"helpDescription": null,
		"helpDescriptionMobile": null,
		"helpMenu": null,
		"join": null,
		"kdAbbr": null,
		"kdRatio": null,
		"killedYou": null,
		"killsAbbr": null,
		"killsDeathsRatio": null,
		"killStreaks": null,
		"killFeed": null,
		"link1": null,
		"link2": null,
		"link3": null,
		"link4": null,
		"loading": null,
		"lobbyButton": null,
		"lobbyGamesTitle": null,
		"lobbyLogout": null,
		"lobbyQuickJoin": null,
		"lobbyTitle": null,
		"loser": null,
		"labs": null,
		"mapVote": null,
		"messageServerMove": null,
		"messageUnlock": null,
		"mode": null,
		"modeCP": null,
		"modeObjCP": null,
		"modeObjTDM": null,
		"modeTDM": null,
		"name": null,
		"newItem": null,
		"okay": null,
		"password": null,
		"pickedUp": null,
		"play": null,
		"playerStats": null,
		"players": null,
		"quitConfirm": null,
		"ratio": null,
		"redTeam": null,
		"replays": null,
		"report": null,
		"reportConfirm": null,
		"respawnClick": null,
		"respawnTimer": null,
		"restoreDefaults": null,
		"save": null,
		"sendUpdates": null,
		"serverConnecting": null,
		"serverFind": null,
		"serverFound": null,
		"serverLoading": null,
		"settings": null,
		"size": null,
		"sizeBig": null,
		"sizeMedium": null,
		"sizeSmall": null,
		"social": null,
		"submit": null,
		"supportButton": null,
		"tie": null,
		"timeUpBlue": null,
		"timeUpRed": null,
		"timeUpTie": null,
		"updateTitle": null,
		"viewInLobby": null,
		"vip": null,
		"VIP-ask": null,
		"VIP-button": null,
		"VIP-congrats": null,
		"VIP-info1": null,
		"VIP-info2": null,
		"VIP-info3": null,
		"VIP-info4": null,
		"VIP-info5": null,
		"VIP-info6": null,
		"VIP-item": null,
		"VIP-pitch": null,
		"weapon_bomb": null,
		"weapon_flashbang": null,
		"weapon_grenade": null,
		"weapon_intro": null,
		"weapon_rapid": null,
		"weapon_rocket": null,
		"weapon_shotgun": null,
		"weapon_sniper": null,
		"weapon_volcano": null,
		"winner": null,
		"XP-level": null,
		"XP-rank": null,
		"youKilled": null
	}
};

var elms = document.querySelectorAll('[text]');
var c = 0;
elms.forEach(function(elm) {
	elm.innerText = translate(elm.getAttribute("text"));
})

function translate(key) {
	if (STRINGS[LANG][key] == undefined || STRINGS[LANG][key] == null) {
		return STRINGS["en"][key];
	}
	else {
		return STRINGS[LANG][key];
	}
}